### ISSUE TITLE
Problem with Composer installation

### ISSUE THREAD

**Issue by dpcat237** [everzet/capifony#516]
Hello,
I try to configure capifony and have a problem strange problem with composer installation.

With this configuration related to composer:

    set :deploy_via,       :capifony_copy_local
    set :use_composer,     true
    set :use_composer_tmp, true
    set :composer_options, "--verbose --prefer-dist --optimize-autoloader"

I have next error:

    Command cd /tmp/deploys/20140723100922 && curl -s http://getcomposer.org/installer | php returned status code pid 25074 exit 127

When I execute the same command (changing folder to this "\tmp") with same user directly in the server it execute without any problem. After trying change the configuration I saw that the same error is printed differently with next configuration:

    set :deploy_via,       :capifony_copy_local
    set :use_composer,     false
    set :use_composer_tmp, false
    set :composer_options, "--verbose --prefer-dist --optimize-autoloader"

Error message:

    failed: "sh -c 'sh -c '\\''cd /var/www/test/releases/20140723100817 && curl -s http://getcomposer.org/installer | php'\\'''" on domain

This command execute properly directly in server only if I remove "\\" after "php".
I was searching in internet about this problem and only found unreplied post with same problem: http://stackoverflow.com/questions/21794963/error-with-capifony-deployment-to-freebsd-system.

Thanks in advance!

**Comment by skolodyazhnyy** [comment]
It seems that now you can not download composer using HTTP, only HTTPS. 

I have tried command from Capifony:
```
curl -s http://getcomposer.org/installer | php
```

And it gives 302 (redirect). It looks like there is no configuration change that can fix it.

**Comment by jiglesiasabio** [comment]
I´m having the same problem, I think this can be fixed by changing the URL to https.

Testing from my machine If I CURL to the http URL i get:
```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I I done the same curl to an https URL everything goes fine!

**Comment by jiglesiasabio** [comment]
Seems to be fixed by PR #567

**Comment by skolodyazhnyy** [comment]
As a workaround you can install `composer` on your server and specify path in your configuration file,

```
set :composer_bin, "/usr/bin/composer.phar"
```

**Comment by jiglesiasabio** [comment]
@skolodyazhnyy Thank you for the workaround!

**Comment by willdurand** [comment]
see #568

**Comment by dpcat237** [comment]
Thanks to all!
