### ISSUE TITLE
Capifony.org down due to misconfiguration

### ISSUE THREAD

**Issue by WouterJ** [everzet/capifony#546]
GitHub Pages recently changed. The admins got an email about this if everything is correct. They should follow these steps in order to get capifony.org back on track

**Comment by willdurand** [comment]
Ah. Did not receive any email...

**Comment by willdurand** [comment]
nevermind... did not see that you closed the issue.

**Comment by WouterJ** [comment]
@willdurand yeah, I closed it as the website is available (so someone changed it between november and now)

**Comment by willdurand** [comment]
yup, I made the changes but forgot to close the issue obviously
