### ISSUE TITLE
SFTP Upload for parameters_prod.yml fails with capistrano-2.15.5, gems 1.8 and net-sftp-2.1.2

### ISSUE THREAD

**Issue by webdevilopers** [everzet/capifony#554]
I am currently forced to use `net-sftp-2.1.2` on `gems 1.8` and `capistrano-2.15.5`.

```ruby
task :upload_parameters do
origin_file = "app/config/parameters_prod.yml"
destination_file = latest_release + "/app/config/parameters.yml" # Notice the latest_release

try_sudo "mkdir -p #{File.dirname(destination_file)}"
top.upload(origin_file, destination_file)
end
```

The SFTP Upload for `parameters_prod.yml` will fail:
```
 ** sftp upload app/config/parameters_prod.yml -> /.../releases/20150108143459/app/config/parameters.yml
*** [deploy:update_code] rolling back
executing "rm -rf /usr/local/www/.../releases/20150106142722; true"
    servers: ["..."]
    [...] executing command
    command finished in 220ms
/var/lib/gems/1.8/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:176:in `initialize': expected a file to upload (ArgumentError)
```

Is there a workaround?

**Comment by webdevilopers** [comment]
It looks like the main problem is that there is no `parameters_prod.yml` since I don't have any `parameters*` files at all inside my git repository.

Do I have to create it once?

**Comment by webdevilopers** [comment]
I've changed my lines in order to copy the regular `parameters.yml` file:
```ruby
set :shared_files,    ["app/config/parameters.yml", "web/.htaccess", "web/uploads"]

task :upload_parameters do
#origin_file = "app/config/parameters_prod.yml"
origin_file = "app/config/parameters.yml"
destination_file = latest_release + "/app/config/parameters.yml" # Notice the latest_release

try_sudo "mkdir -p #{File.dirname(destination_file)}"
top.upload(origin_file, destination_file)
end
```

But at the end of deployment symfony can not connect to the database since the parameters from my local app aren't the same as on the production server.

So instead I guess I have to copy the `shared/app/config/parameters.yml` there which I configured correctely.

What is the placeholder for the shared folder similar to `latest_release`?

**Comment by KrunoKnego** [comment]
From what I can gather you only have to create new parameteres_prod.yml file with information your server's information. Uncomment 

    origin_file = "app/config/parameters.yml"

and comment 

   origin_file = "app/config/parameters.yml"

**Comment by webdevilopers** [comment]
But the task will look for the`parameters_prod.yml` file on my locale machine, right?
For security reasons we are not pushing any parameters to our git repository.
Meaning that every developer will have to create the prod file once AND to adapt changes.
But if someone forgets changed credentials and deploys the file...

Actually I thought that the task would follow the recommended process in the docs:
```
The final step is to configure your app/config/parameters.yml file. The best way to do this is to create this file in shared folder on server manually:

ssh your_deploy_server
mkdir -p /var/www/my-app.com/shared/app/config
vim /var/www/my-app.com/shared/app/config/parameters.yml

Once your parameters.yml file is correctly configured, you should be able to test your deployed application. On every subsequent deploy, that same app/config/parameters.yml file will be symlinked into your application, meaning you only need to configure after the initial deploy.
```
http://capifony.org/#symfony2-deployment

**Comment by webdevilopers** [comment]
Anyway, I have integrated the Multistage extension. On a first deploy `Symfony` will ask me to enter the parameters to auto-create them.

The offical `Capifony` docs feature a working example. I use that approach instead of the one provided by @KrunoKnego:
http://krunoknego.com/2014/09/30/deploying-symfony2-applications-with-capifony/

Closing.

**Comment by webdevilopers** [comment]
BTW @KrunoKnego :+1: 
When sharing my `.htaccess` and deploying it for the first time the symlinked file under `shared/web/.htaccess` wil be empty.
Guess I will have to fill it manually too or is it an unexpected behaviour?
