### ISSUE TITLE
assets_update_version error

### ISSUE THREAD

**Issue by tunh** [everzet/capifony#565]
* 2015-04-18 12:15:26 executing `symfony:assets:update_version'
--> Updating `assets_version`
  * executing "find /home/example/dev.acme.com/releases/20150418051523/web/css /home/example/dev.acme.com/releases/20150418051523/web/images /home/example/dev.acme.com/releases/20150418051523/web/js -type f -printf '%Ts\\n' | sort -n | tail -1"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
[err :: 127.0.0.1] find: `/home/example/dev.acme.com/releases/20150418051523/web/css'
[err :: 127.0.0.1] : No such file or directory
find: `/home/example/dev.acme.com/releases/20150418051523/web/images': No such file or directory
[err :: 127.0.0.1] find: `/home/example/dev.acme.com/releases/20150418051523/web/js': No such file or directory
    command finished in 128ms
    Latest assets version: (0)
  * executing "echo 'parameters:\\n    assets_version: 0' |  tee /home/example/dev.acme.com/releases/20150418051523/app/config/assets_version.yml"
    servers: ["127.0.0.1"]
    [127.0.0.1] executing command
 ** [out :: 127.0.0.1] parameters:\n    assets_version: 0
    command finished in 126ms

I think capifony 2.8.4 has a bug in assets_update_version. Capifony 2.8.3 is still okay!

assets_version.yml content:
parameters:\n    assets_version: 0

**Comment by tomtomau** [comment]
We're having some issues with this after updating from 2.8.3 -> 2.8.5 for the Composer fix.

Correct me if I'm wrong, but shouldn't this command be run after composer has installed dependencies and the cache is warmed up etc?

**Comment by tunh** [comment]
I used v2.8.4 not v2.8.5. I think there are some issues from symfony:assets:update_version in v2.8.4. Everything is okay in v2.8.3. Errors as I showed above.

**Comment by aaslocum** [comment]
Same worked for me, rolled back to 2.8.3, couldnt resolve the error in 2.8.5
