### ISSUE TITLE
Rsync with local composer update

### ISSUE THREAD

**Issue by charlieWasp** [everzet/capifony#566]
Hello! I want to ask - is there an option for using local copy of vendors but transfer all code via rsync instead of sftp?

**Comment by la5942** [comment]
There is not. You would have to edit the [copy_local](https://github.com/everzet/capifony/blob/master/lib/capistrano/recipes/deploy/strategy/capifony_copy_local.rb) or create a new deploy strategy that uses [capistrano_rsync_with_remote_cache](https://github.com/vigetlabs/capistrano_rsync_with_remote_cache) and possibly update the [strategy](https://github.com/vigetlabs/capistrano_rsync_with_remote_cache/blob/master/lib/capistrano/recipes/deploy/strategy/rsync_with_remote_cache.rb) for it to work correctly.
