### ISSUE TITLE
Composer install does not work anymore

### ISSUE THREAD

**Issue by ohmytribe** [everzet/capifony#570]
Composer installer does not work anymore.

It seems that Composer site now is redirecting all http requests to https. This prevents composer from being installed.

**Comment by tyomo4ka** [comment]
Proper fix is in #568. @everzet @willdurand Could you check that PR and release new version. Everyone is affected by this.

**Comment by ohmytribe** [comment]
@tyomo4ka not sure how adding -S to curl command is related to the initial issue. Adding -L option tells curl to follow location that will help to avoid any issues if installer URL will be permanently moved to somewhere else by 302 redirect.
```
        -L, --location
              (HTTP/HTTPS) If the server reports that the requested page has moved to a different location (indicated with a Location: header and a 3XX response code), this option will make curl redo
              the request on the new place.
```
```
       -S, --show-error
              When used with -s it makes curl show an error message if it fails.
```

**Comment by raistlin** [comment]
In http://getcomposer.org/download they provide current command to install composer
````
curl -sS https://getcomposer.org/installer | php
````

We should stick with it.

**Comment by tyomo4ka** [comment]
@ohmytribe Yep `-L` could prevent from similar issues in the future. But the difference is in `https` instead of `http`. `-S` just to follow recommended installation command from the official documentation.

**Comment by nietonfir** [comment]
@tyomo4ka Exactly. :+1:

**Comment by rolebi** [comment]
:+1:

**Comment by niepi** [comment]
:+1:

**Comment by LegendPJ** [comment]
:+1:

**Comment by chapa** [comment]
:+1:

**Comment by willdurand** [comment]
see #568
